### ISSUE TITLE
Does Gobblin support deduplication compaction with Gobblin on YARN mode 

### ISSUE THREAD

**Issue by bit1129** [linkedin/gobblin#1342]
Hi，
I am able to run deduplication compaction with gobblin-compation.sh which is based on MapReduce.I am
evaluating whether deduplication compaction is supported by Gobblin on YARN mode? It looks to me that the answer is NO, and what Gobblin on YARN supports are Source/Extractor/Writer work flow?
Since there is not much documentation ,please kindly help me on this question, Thanks a lot!!!!

**Comment by bit1129** [comment]
@abti @ibuenros Could you guys please take a look at my question? thanks!

**Comment by ibuenros** [comment]
Hi,
Gobblin compaction is simply a convenience MapReduce job, outside of the
Gobblin ingestion framework. All of the distributed computation is done
through MR using Hadoop 2 APIs, so it should work seamlessly on YARN, but
it is not a YARN native application. What yarn features would you want from
compaction that you are not getting?
Issac

**Comment by abti** [comment]
Anything that can run (including compaction) in Gobblin MR mode can run on Gobblin on Yarn. However, since MR is an user land library / application that can run on top of Yarn. You can simply run Gobblin MR compaction on your Yarn cluster. 

Or are you using Gobblin on Yarn for running other use cases as well?
