### ISSUE TITLE
[Help Needed] Print out some stats from Gobblin

### ISSUE THREAD

**Issue by jeffwang66** [linkedin/gobblin#1453]
Hi,

I am running Gobblin on Hadoop. I have my own writer and publisher class.  Each writer collects some stats (e.g.  number of processed records). I just would like to ask if the publisher can get such stats from each writer.

Also, it there any internal Gobblin property to record the execution time of each task unit and the total execution time of Gobblin job?

Thanks

**Comment by wosiu** [comment]
To record execution time of each task you can extend:
https://github.com/linkedin/gobblin/blob/7141ec88c255c8c3cbc7054fb8146eebe77fc09d/gobblin-metrics-libs/gobblin-metrics-base/src/main/java/gobblin/metrics/reporter/ScheduledReporter.java
To create custom reporter (https://gobblin.readthedocs.io/en/latest/metrics/Metrics-for-Gobblin-ETL/#custom-reporters). Each mapper gets one of these, so you can System.time in startImpl() and measure diff in stopImpl so that you've got time per task. You'e got there nice metrics too.
However I'm also interested how to measure whole job time within gobblin. Now I'm just taking hadoop job time using yarn client outside gobblin.
