### ISSUE TITLE
using fork operator with two different Data Publishers

### ISSUE THREAD

**Issue by cvaliente** [linkedin/gobblin#1766]
Hi,

I want to publish data to a kafka topic and to hdfs and I have all the DataWriters and the Fork in place and running.
Now I want to use the TimePartitionedDataPublisher for the hdfs branch and the NoopPublisher for the kafka branch, but it doesn't seem to be possible. setting data.publisher.type.# is ignored. Also, data.publisher.type is marked as deprecated in ConfigurationKeys but the documentation still uses that, and the ones replacing it are mentioned nowhere.

I also found some more inconsistencies with branch specific settings, WRITER_FILE_PATH_TYPE and WRITER_PARTITIONER_CLASS seems to only have a global scope as well and cannot be set on a per branch basis.

**Comment by eogren** [comment]
Hey Clemens -

Thanks for the great questions. I’m going to handle them in easiest-hardest to answer..

- I actually don’t think data.publisher.type should be marked as deprecated — we certainly use it in a bunch of our jobs as well. (And certainly not without updating the examples!) Let me check internally and probably remove the comment. 

- Yep, WRITER_FILE_PATH_TYPE is just a bug — we will fix! We recognize that in general the config can be confusing for end-users, and the design inside the system makes it hard to figure to how to map config to the various converters/writers that consume it.

- In general, it’s best practice to actually set up two jobs to dual write like this. The major reasons for this are around failure:
   1. We don’t have the ability to keep track of per-fork watermarks so, if, say, a write to HDFS fails and the overall job fails, you’ve already written a bunch of data of Kafka and we will re-write all this data when the job is restarted. 
   2. Even stranger would be if you had two different publishers and one publisher succeeded and one failed - does the 1st publisher have to unpublish the dataset somehow? What does published mean in this scenario?

The second case is why we only have one Publisher per job. That said this should obviously be better documented.

does that make sense?

**Comment by shirshanka** [comment]
To provide a slightly different perspective to @eogren's answer, if you need to get the same data to Kafka and HDFS, you can take one of two "recommended" paths: 

 a) Set up two independent jobs reading from your source and writing to Kafka and HDFS respectively. This may work if redundantly reading from the source is not a problem, or if you are trying to have separate pipelines for data to Kafka and HDFS so you can do audits later. 

 b) Set up one pipeline to read from the source and write to Kafka. Set up another to read from Kafka and write to HDFS. In this case, you are basically using Kafka as your derived source of truth for the transport, so if you have any data loss in Kafka, you see it in HDFS as well. This may be the preferred option in many cases, because extracting changes from the source can often be the bottleneck. 

 Using forks in Gobblin to write to two completely different systems (with different uptimes / guarantees) is not something we recommend in general. 

HTH
Shirshanka

**Comment by cvaliente** [comment]
thanks a lot @shirshanka and @eogren 
Ultimately my goal is to have an audit log in Kafka of how many messages gobblin has written to hdfs. I think I kind of got it working but I am not quite happy how it turned out. (basically a re-implementation of the AsyncBestEffortDataWriter)

I also had a look at the gobblin-audit subproject which seems to have the same goal in mind.
While its implementation seems fairly straightforward, I didn't find anything on its integration within a gobblin job and the documentation seems rather sparse

**Comment by shirshanka** [comment]
@cvaliente : Ok, this use-case does make a lot of sense. Did you consider using Gobblin's metrics capability and the metrics reporter to Kafka to accomplish this? 

https://gobblin.readthedocs.io/en/latest/metrics/Gobblin-Metrics/#metrics

What sort of audit are you trying to do? 
Simple count-based / more complex ?

**Comment by cvaliente** [comment]
The metrics reporter was actually the first thing I looked at before moving on.
Ideally I would like to emit counts per specific time window based on the message's timestamp - identical to the audits that our message producers emit. This way I can get a perfect 1:1 match between gobblin consumer audits and producer audits - if all works well, of course. 
The metrics reporter didn't seem to support that without major changes.
The fork with a kafka audit writer and a hdfs writer branch seems to work fine now. The logging to kafka only happens in the commit phase of the datawriter, so only after all the data has been written to hdfs. I won't get transactional behaviour out of kafka, it will always be on a best effort basis, but if the producer and consumer message count match I can be fairly confident all my data is on the hdfs.

**Comment by shirshanka** [comment]
@cvaliente Seems reasonable. A few questions for me to help understand your requirements better: What semantics are you trying to achieve with the audit pipeline (exactly-once, at-least-once, at-most-once or best-effort)?
Some examples below: 
1 [best-effort] If a record was written (and committed) on HDFS, there must be one corresponding audit aggregate record that contains it, but there could be audit records for records that were not finally written to HDFS. 
2 [at-most-once] If there is an audit-record, there must be a contributing data record that was written and committed to HDFS, but there could be records on HDFS that don't have an audit record. 
3 [at-least-once] For each record on HDFS, there is one or more corresponding audit-records in the audit-stream. There are no audit-records that contain aggregates for uncommitted data. 
3 [exactly-once] Each audit-record has a corresponding set of records on HDFS, each record on HDFS has a corresponding audit-record. Each audit-record is only found once in the audit stream. 

In a streaming (best-effort style) pipeline, you can achieve 1 by attaching a converter in your pipeline that inspects records passing through, creates the audit-record and sends it out to Kafka once the time-window is done. (This is generally how the producer audit in Kafka producer works IIRC)

To achieve 2 (at-most-once) in a batch pipeline, it might be better to write audit records to HDFS to the same staging dir as data and move them during your HDFS commit (data will be committed atomically with metadata). You then need another stage to emit these committed audit records to Kafka. I believe there is a post-publish stage that Gobblin supports. If you have a ton of audit records, this allows you to offload the storage of these to HDFS (instead of holding on to them in memory until you emit to Kafka). This strategy is at-most-once because the post-publish stage could fail but the data is already committed. 

To achieve 3 [at-least-once], you could actually run a separate Gobblin pipeline whose only job is to find the audit-records on HDFS and emit them to Kafka with acks set to max. 

4 [exactly-once] is pretty hard to get since this is in the limit doing 2PC between HDFS and Kafka. 

So which semantic are you trying to achieve?

**Comment by cvaliente** [comment]
The ultimate goal is to be able to answer
"Did gobblin already pull in all of yesterday's (expected) data?" 
before starting batch processes on hadoop going over that data.

So I believe I am going for 2 (at-most-once). If the producer audit and the consumer audit match, all the data needs to be on hdfs. if the audit doesn't match, it could be that we lost data somewhere in our pipeline, or because the post-publish step failed. 
Thanks for your feedback and suggestions! I will have to look at how to implement such a post-publish stage.
