### ISSUE TITLE
Not compatible with Confluent's schema registry 

### ISSUE THREAD

**Issue by yiming187** [linkedin/gobblin#465]
Hello, I found the gobblin's schema registry client fetch the schema by topic name, but in Confluent's schema registry, all topic's schema names are end with '-value', for example 'AAA-value'. So the KafkaAvroExtractor will throw out: Cannot find latest schema for topic 'AAA'.

**Comment by zliu41** [comment]
Hi @yiming187 we've decoupled the schema registry implementation with `KafkaAvroExtractor` in #461. Now you can use any implementation of `KafkaSchemaRegistry` and use it with an implementation of `KafkaAvroExtractor`. It will be great if you can add the Confluent schema registry client to the repo since we'd like to be able to support it out of the box.

**Comment by shirshanka** [comment]
This is done. 

See: http://gobblin.readthedocs.io/en/latest/case-studies/Kafka-HDFS-Ingestion/#confluent-integration
