### ISSUE TITLE
Task metrics are not saved to Job History Database when running under Yarn

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#748]
Task level metrics are not transmitted from the containers that tasks are running on back to the app_master.  This means that task level metrics cannot be saved in the Job History Database.  We should be able to store the task level metrics in the Job History Database just like when we run a standalone job.

**Comment by ydai1124** [comment]
@kadaan We are deprecating the Job/Task metrics you are using. It is better to switch to Gobblin Metrics: https://github.com/linkedin/gobblin/wiki/Gobblin%20Metrics%20Architecture. It has more contents and more stable. But we don't have the reporter to report to database yet. You can implement your own reporter: https://github.com/linkedin/gobblin/wiki/Implementing%20New%20Reporters.

**Comment by sahilTakiar** [comment]
@kadaan is this bug blocking the deployment of the `JobHistoryStore` or are you actually interesting in viewing the `TaskMetrics`? Just want to understand where the bug is.

AS @ydai1124 mentioned we are moving away from `TaskMetrics` and `JobMetrics`, and at some point we want to remove the current way `TaskMetrics` and `JobMetrics` are written to the `JobHistoryStore`.

**Comment by kadaan** [comment]
No, it is not blocking anything.
