### ISSUE TITLE
addShutdownHook is causing a leak

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#802]
@sahilTakiar As far as I can tell, the addition of shutdown hooks are causing a leak: [oom_heapdump_Leak_Suspects.zip](https://github.com/linkedin/gobblin/files/161907/oom_heapdump_Leak_Suspects.zip)

**Comment by sahilTakiar** [comment]
hmmm, this is Gobblin on YARN right? I'm guessing this was introduced in: https://github.com/linkedin/gobblin/pull/741

`AbstractJobLauncher` adds a new shutdown hook for each job. Since Gobblin on YARN is continuously running these shutdown hooks never get invoked when a job completes. The fix is to move this shutdown hook to the `ApplicationLauncher`. I will take care of this as part of the work for https://github.com/linkedin/gobblin/issues/792 (should have a PR by EOD today)

**Comment by kadaan** [comment]
Yes. It also seems to be important to call `remoteShutdownHook`.

**Comment by sahilTakiar** [comment]
Fixed in #808
