### ISSUE TITLE
Metrics hard to enable when run as standalone mode

### ISSUE THREAD

**Issue by ibuenros** [linkedin/gobblin#916]
When Gobblin is launched as standalone, `SchedulerDaemon` starts all Gobblin services (including Gobblin metrics) using the system and custom configurations, but not the job configurations. Usually, users will specify their metrics config in the job configuration, but this means that for standalone, those configurations will be skipped.
Users must specify metrics configurations using the `--conffile` flag. This needs to be fixed or at least documented.

**Comment by sahilTakiar** [comment]
When launching in stand-alone mode, users can just add the metrics configs to `conf/gobblin-standalone.properties`, there is no need to use `--conffile`.

Given the current way Gobblin Metrics works, I think it makes more sense for metrics to be placed in the `.properties` file rather than the `.job` files, and I think we should change the documentation to reflect that. This issue documents the problems with Gobblin Metrics before the Metrics-as-a-Service feature was added: https://github.com/linkedin/gobblin/issues/792
